version: "3"
services:
  strapi:
    container_name: strapi-librairie-app
    image: neo7studioweb/strapi-librairie
    restart: unless-stopped
    env_file: stack.env
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_HOST: strapiDB
      DATABASE_PORT: 3306
      DATABASE_NAME: ${MARIADB_DATABASE}
      DATABASE_USERNAME: ${MARIADB_USERNAME}
      DATABASE_PASSWORD: ${MARIADB_PASSWORD}
      DATABASE_SSL: 'false'
    volumes:
      - ./app:/srv/app

    ports:
      - 1338:1337
    networks:
      - strapi
    depends_on:
      - strapiDB

  strapiDB:
    container_name: strapiDB
    restart: unless-stopped
    env_file: stack.env
    image: mariadb:latest
    environment:
      MARIADB_USER: ${MARIADB_USERNAME}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
    volumes:
      - strapi-librairie-data:/var/lib/mysql
      #- ./data:/var/lib/mysql # if you want to use a bind folder
    ports:
      - 3308:3306
    networks:
      - strapi

  phpmyadmin:
    image: phpmyadmin:latest
    restart: unless-stopped
    ports:
      - 8088:80
    networks:
      - strapi
    depends_on:
      - strapiDB
    environment:
      - PMA_HOST=strapiDB

volumes:
  strapi-librairie-data:

networks:
  strapi:
    name: Strapi
    driver: bridge